import{a as c,S as d,i as u}from"./assets/vendor-c8cb2b96.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerpolicy&&(o.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?o.credentials="include":r.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();c.defaults.headers.common["x-api-key"]="live_8CoVBLC9aZolICXzvyyxeEAcUbJcBLCBfeHB03Q0jVss9sHPS8qokxRh5dbP8Kg4";const f="https://api.thecatapi.com/v1/breeds",m="https://api.thecatapi.com/v1/images/search?";function h(){return c({url:f}).then(t=>{if(t.status!==200)throw new Error("Sorry, but cats have been finished!!");return t.data})}function p(t){const e=`${m}breed_ids=${t}`;return c({url:e}).then(n=>{if(n.status!==200)throw new Error("Sorry, but cats have been finished!!");return n.data[0]})}const s={select:document.querySelector(".js-breed-select"),selectWrapper:document.querySelector(".js-select-wrapper"),catInfo:document.querySelector(".js-cat-info"),loader:document.querySelector(".js-loader"),error:document.querySelector(".js-error")},g=new d({select:s.select,data:[]});function y(t){return t.map(({id:e,name:n})=>({value:e,text:n}))}function v({url:t,breeds:e}){return`<div class="cat-info__image-thumb"><img class="cat-info__image" src="${t}" alt="${e[0].name}" width="350" /></div>
  <div class="cat-info__detais">
    <div>
      <h2 class="cat-info__title">${e[0].name}</h2>
      <p class="cat-info__description">${e[0].description}</p>
    </div>
    <div class="cat-info__temperament">
      <h3 class="cat-info__temperament-title">Temperament</h3>
      <p class="cat-info__temperament-text">${e[0].temperament}</p>
    </div>
  </div>`}function l(){u.show({message:"Oops! Something went wrong! Try reload the page!",close:!1,closeOnClick:!0,position:"topRight",messageColor:"#fff",backgroundColor:"#d60808"})}h().then(t=>{s.selectWrapper.classList.remove("hidden"),g.setData(y(t))}).catch(t=>{console.log(t.message),l()}).finally(()=>s.loader.classList.add("hidden"));s.select.addEventListener("change",({target:{value:t}})=>{s.loader.classList.remove("hidden"),s.catInfo.innerHTML="",p(t).then(e=>{s.catInfo.insertAdjacentHTML("beforeend",v(e))}).catch(e=>{console.log(e.message),l()}).finally(()=>s.loader.classList.add("hidden"))});
//# sourceMappingURL=commonHelpers.js.map
