import{a as i,S as d,i as u}from"./assets/vendor-c8cb2b96.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerpolicy&&(o.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?o.credentials="include":r.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();i.defaults.headers.common["x-api-key"]="live_8CoVBLC9aZolICXzvyyxeEAcUbJcBLCBfeHB03Q0jVss9sHPS8qokxRh5dbP8Kg4";const f="https://api.thecatapi.com/v1/breeds",h="https://api.thecatapi.com/v1/images/search?";function m(){return i({url:f}).then(e=>{if(e.status!==200)throw new Error("Sorry, but cats have been finished!!");return e.data})}function p(e){if(!e)return;const t=`${h}breed_ids=${e}`;return i({url:t}).then(s=>{if(s.status!==200)throw new Error("Sorry, but cats have been finished!!");return s.data[0]})}const n={select:document.querySelector(".js-breed-select"),selectWrapper:document.querySelector(".js-select-wrapper"),catInfo:document.querySelector(".js-cat-info"),loader:document.querySelector(".js-loader"),error:document.querySelector(".js-error")},y=new d({select:n.select,data:[],settings:{placeholderText:"Choose your kitty"},events:{afterChange:e=>_(e)}});m().then(e=>{n.selectWrapper.classList.remove("hidden"),y.setData(g(e))}).catch(e=>{console.log(e.message),l()}).finally(()=>n.loader.classList.add("hidden"));function g(e){const t=e.map(({id:s,name:a})=>({value:s,text:a}));return t.unshift({value:"",text:"Choose your kitty"}),t}function v({url:e,breeds:t}){return`<div class="cat-info__image-thumb"><img class="cat-info__image" src="${e}" alt="${t[0].name}" width="350" /></div>
  <div class="cat-info__detais">
    <div>
      <h2 class="cat-info__title">${t[0].name}</h2>
      <p class="cat-info__description">${t[0].description}</p>
    </div>
    <div class="cat-info__temperament">
      <h3 class="cat-info__temperament-title">Temperament</h3>
      <p class="cat-info__temperament-text">${t[0].temperament}</p>
    </div>
  </div>`}function l(){u.show({message:"Oops! Something went wrong! Try reload the page!",close:!1,closeOnClick:!0,position:"topRight",messageColor:"#fff",backgroundColor:"#d60808"})}function _(e){const t=e[0].value;t&&(n.loader.classList.remove("hidden"),n.catInfo.innerHTML="",p(t).then(s=>{n.catInfo.insertAdjacentHTML("beforeend",v(s))}).catch(s=>{console.log(s.message),l()}).finally(()=>n.loader.classList.add("hidden")))}
//# sourceMappingURL=commonHelpers.js.map
